[tool.poetry]
name = "turtle-backtest"
version = "0.1.0"
description = "Backtest different US stocks trading strategies"
authors = ["Jaak Niit <jaak.niit@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
alpaca-py = "^0.28.0"
python-dotenv = "^1.0.1"
yfinance = "^0.2.40"
psycopg-binary = "^3.2.1"
psycopg = "^3.2.1"
pandas = "^2.2.2"
ta-lib = "^0.4.32"
numpy = "^1.26.4"
streamlit = "^1.37.1"
pytest = "^8.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
