[project]
name = "turtle"
version = "0.2.0"
description = "Backtest different US stocks trading strategies"
authors = [{ name = "Jaak Niit", email = "jaak.niit@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "alpaca-py>=0.40.2",
    "python-dotenv>=1.0.1",
    "yfinance>=0.2.40",
    "psycopg[binary,pool]>=3.2.1",
    "pandas>=2.2.2",
    "ta-lib>=0.6.4",               # Requires system library: https://github.com/TA-Lib/ta-lib-python#troubleshooting
    "numpy>=2.0.0",                # Upgraded to NumPy 2.0 (TA-Lib 0.6.4+ supports it)
    "streamlit>=1.37.1",
    "types-requests>=2.32.0.20240712",
    "setuptools>=74.1.2",
    "backtesting>=0.3.3",
    "bokeh==2.4.3",
    "plotly>=5.24.1",
]

[project.optional-dependencies]
dev = ["pytest>=8.3.2", "pytest-mock>=3.14.0", "jupyter>=1.1.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["turtle"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:websockets.legacy.*",
]
