#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE trading
        WITH
        OWNER = postgres
        ENCODING = 'UTF8'
        LC_COLLATE = 'en_US.UTF-8'
        LC_CTYPE = 'en_US.UTF-8'
        TEMPLATE = template0;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "trading" <<-EOSQL
    -- alembic: full access for migrations
    CREATE USER alembic WITH PASSWORD '${DB_ALEMBIC_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE trading TO alembic;

    CREATE SCHEMA IF NOT EXISTS turtle AUTHORIZATION alembic;
    GRANT ALL ON SCHEMA turtle TO alembic;
    ALTER DEFAULT PRIVILEGES IN SCHEMA turtle GRANT ALL ON TABLES TO alembic;
    ALTER DEFAULT PRIVILEGES IN SCHEMA turtle GRANT ALL ON SEQUENCES TO alembic;
    ALTER DEFAULT PRIVILEGES IN SCHEMA turtle GRANT ALL ON FUNCTIONS TO alembic;
    
    GRANT ALL ON SCHEMA public TO alembic;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO alembic;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO alembic;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO alembic;

    -- app_user: read/write access to turtle schema (application user)
    CREATE USER app_user WITH PASSWORD '${DB_APP_PASSWORD}';
    GRANT CONNECT ON DATABASE trading TO app_user;
    GRANT USAGE ON SCHEMA turtle TO app_user;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA turtle TO app_user;
    GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA turtle TO app_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA turtle GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA turtle GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app_user;

    -- claude: readonly access to turtle schema
    CREATE USER claude WITH PASSWORD '${DB_CLAUDE_PASSWORD}';
    GRANT CONNECT ON DATABASE trading TO claude;
    GRANT USAGE ON SCHEMA turtle TO claude;
    GRANT SELECT ON ALL TABLES IN SCHEMA turtle TO claude;
    ALTER DEFAULT PRIVILEGES IN SCHEMA turtle GRANT SELECT ON TABLES TO claude;
    ALTER DEFAULT PRIVILEGES IN SCHEMA turtle GRANT SELECT ON SEQUENCES TO claude;
EOSQL
