name: Build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  

    #- name: Install system dependencies for ta-lib
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y build-essential autoconf automake libtool
    #    sudo apt-get install -y libta-lib0 libta-lib0-dev        

    - run: |
        wget https://sourceforge.net/projects/ta-lib/files/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz
        tar xvfz ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure
        make
        sudo make install

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install

    # - name: Run mypy for static type checking
    #   run: poetry run mypy turtle/ tests/ main.py app.py

    - name: Run tests
      run: poetry run pytest